# Generated by Django 4.2.1 on 2023-05-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_attendance_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attend',
            field=models.BooleanField(default=False),
        ),
    ]
