# Generated by Django 4.2.1 on 2023-05-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_attendance_attend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='working_period',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
