# Generated by Django 4.2.1 on 2023-05-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_attendance_working_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='working_period',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
