# Generated by Django 4.2.1 on 2023-05-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_datetimenow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateTimeNow',
        ),
    ]
