# Generated by Django 4.2.1 on 2023-05-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_datetimenow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
