# Generated by Django 4.2.1 on 2023-05-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_datetimenow'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimenow',
            name='lateInTimeLimit',
            field=models.TimeField(default='11:10:00'),
        ),
    ]
