# Generated by Django 4.2.1 on 2023-05-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_datetimenow_lateintimelimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateInTimeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='datetimenow',
            name='lateInTimeLimit',
        ),
    ]
