# Generated by Django 4.2.1 on 2023-05-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_lateintimelimit_remove_datetimenow_lateintimelimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTimeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JustInTime', models.TimeField()),
                ('LateInTimeLimit', models.TimeField()),
                ('JustOutTime', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='LateInTimeLimit',
        ),
    ]
