# Generated by Django 4.2.1 on 2023-05-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_attendancetimelimit_delete_lateintimelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='early_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='early_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
