# Generated by Django 4.2.1 on 2023-05-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_holidays'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='holidays',
            new_name='holiday',
        ),
    ]
