# Generated by Django 4.2.1 on 2023-05-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_holidays_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
