# Generated by Django 4.2.1 on 2023-06-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_leaveapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='admin_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
